library("MASS")
par(mfrow=c(4,4))
data("hills")
attach(hills)
hist(climb, main="Histogram of climb", xlab="climb")
hist(dist, main="Histogram of dist", xlab="dist")
d = density(climb)
plot(d, col = "red", lwd = 2, main="Dichtekurve von climb")
plot(density(dist), col = "blue", lwd = 2, main="Dichtekurve von dist")
detach(hills)
boxplot(climb, main="Boxplot von climb")
boxplot(dist, main="Boxplot von dist")
qqnorm(climb, main="Q-Q Plot von climb")
qqline(climb, col="red", lwd=2)
qqnorm(dist, main="Q-Q Plot von dist")
qqline(dist, col="red", lwd=2)
#logarithmische Daten
logclimb = log(climb)
logdist = log(dist)
hist(logclimb, main="Histogram von log(climb)", xlab="log(climb)")
hist(logdist, main="Histogram von log(dist)", xlab="log(dist)")
qqnorm(logclimb, main="Q-Q Plot von log(climb)")
qqline(logclimb, col="red", lwd=2)
qqnorm(logdist, main="Q-Q Plot von log(dist)")
qqline(logdist, col="red", lwd=2)